include_guard(DIRECTORY)

list(PREPEND CMAKE_MODULE_PATH "${NETLIFY_CMAKE_PACKAGES}")
list(PREPEND CMAKE_MODULE_PATH "${NETLIFY_CMAKE_MODULES}")
list(APPEND CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake")
list(APPEND CMAKE_MESSAGE_CONTEXT "${PROJECT_NAME}")

include(CMakePrintHelpers)
include(GNUInstallDirs)

unset(project-name)
